"Applied fix from trunk for revision: 1355660  " ------------------------------------------------------------------------ r1355660 | jleroux | 2012-06-30 10:15:42 +0200 (sam., 30 juin 2012) | 10 lines
"Login out on a cluster handled by DeltaManager causes a NPE" https://issues.apache.org/jira/browse/OFBIZ-4289

Uses a HashMap instead of a FastMap here because else we get this kind of error when OFBiz is shut down:

2012-06-12 10:35:29,921 (OFBiz_Shutdown_Hook) [ StandardSession.java:1567:WARN ] Cannot serialize session attribute LAST_VIEW_PARAMS for session 00C48D0D76821C98403482FAE8B77C24.jvm1
java.io.NotSerializableException: net.sf.json.JSONObject
at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1164)
at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:330)
at javolution.util.FastMap.writeObject(FastMap.java:1513)

------------------------------------------------------------------------


git-svn-id: https://svn.apache.org/repos/asf/ofbiz/branches/release12.04@1355661 13f79535-47bb-0310-9956-ffa450edef68