"Applied fix from trunk for revision: 1726828  " ------------------------------------------------------------------------ r1726828 | jleroux | 2016-01-26 16:43:17 +0100 (mar. 26 janv. 2016) | 22 lignes
Fixes "Error on the Split Payment button from the Quick Finalize Order screen" https://issues.apache.org/jira/browse/OFBIZ-6743

Error in trunk:
ERROR rendering error page [/error/error.jsp], but here is the error text: org.ofbiz.webapp.control.RequestHandlerException: No definition found for view with name [checkoutpayment]
Error in stable and old:
org.ofbiz.webapp.control.RequestHandlerException: No definition found for view with name [checkoutpayment]

Vyom Jain added a comment - 22/Nov/15 07:50
This is an issue even in 09.04 and 10.04 code, so it has been there for sometime now.

Scott Gray added a comment - 03/Jan/16 05:43
The view-map was moved to ecommerce in r544053. Probably because the view-map wasn't referenced in the controller.xml for ordermgr. It is actually used though as a view override in component://order/webapp/ordermgr/entry/checkoutoptions.ftl
Just needs to be restored in the controller and have the screen moved back.

jleroux: So I moved back from ecommerce to order (with few adaptations)
* the checkoutpayment.ftl file 
* the order controller view-map
* the screen name checkoutpayment

I tested in both order and ecommerce, works! I will try to backport, let's see...


------------------------------------------------------------------------


git-svn-id: https://svn.apache.org/repos/asf/ofbiz/branches/release15.12@1726829 13f79535-47bb-0310-9956-ffa450edef68