"Applied fix from trunk for revision: 1070230" ------------------------------------------------------------------------ r1070230 | jleroux | 2011-02-13 13:55:45 +0100 (dim., 13 févr. 2011) | 27 lines
A patch from Stephen Rufle "Blank year in UtilValidate.isYear should return false" (https://issues.apache.org/jira/browse/OFBIZ-4171) - OFBIZ-4171

UtilValidate.isYear returns true for a blank year which the calling function UtilValidate.isDate(String, String, String) tries to parse. This causes an exception to be thrown
ValidateMethod.java:96 :ERROR] [ValidateMethod.exec] Error in validation method isDateAfterToday of class org.ofbiz.base.util.UtilValidate: null
I found this error when trying to add a new credit card in the eCommerce checkout flow.
   1. Add a product to the cart
   2. login as any user I used "admin"
   3. Checkout Step "Shipping Address" (Step 1: Where shall we ship it?)
          * Click Next
   4. Checkout Step "Shipping Options" (Step 2: How shall we ship it?)
          * Choose "UPS Air"
          * Click Next
   5. Checkout Step "Payment Options" (Step 3: How shall you pay?)
   6. Create "Credit Card"
          * Fill Name
          * Card Type "Visa"
          * Card Number "4111111111111111"
          * Expiration Date Month drop-down 01
          * Expiration Date Year drop-down leave blank
          * Choose billing address
          * Click "Save" button

Should see "Error in validation method isDateAfterToday of class org.ofbiz.base.util.UtilValidate: null"

My fix is to change isYear, isMonth, and isDay to return false when a blank value is entered.
After I make my change the message is "The expiration date is before today"

------------------------------------------------------------------------


git-svn-id: https://svn.apache.org/repos/asf/ofbiz/branches/release10.04@1070232 13f79535-47bb-0310-9956-ffa450edef68